# Generated by Django 3.2 on 2022-04-15 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_address_zipcode'),
    ]

    operations = [
        migrations.RunSQL("","")
    ]
