# Generated by Django 3.2 on 2022-04-20 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename__id_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
    ]
